[dependencies]
aws-config = "0.55"
aws-sdk-s3 = "0.28"
tokio = { version = "1.0", features = ["full"] }
bytes = "1.0"
polars = "0.39"
pyo3 = "0.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
num_cpus = "1.13"
